CREATE DATABASE IF NOT EXISTS bd_medicos;
CREATE DATABASE IF NOT EXISTS bd_pacientes;
CREATE DATABASE IF NOT EXISTS bd_citas;
CREATE DATABASE IF NOT EXISTS bd_especialidades;
CREATE DATABASE IF NOT EXISTS bd_historial;
CREATE DATABASE IF NOT EXISTS bd_notificaciones;
CREATE DATABASE IF NOT EXISTS bd_pagos;
CREATE DATABASE IF NOT EXISTS bd_recetas;
