spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty=DEBUG

spring.cloud.gateway.routes[0].id=pacientes-service
spring.cloud.gateway.routes[0].uri=lb://pacientes-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/pacientes/**

spring.cloud.gateway.routes[1].id=citas-service
spring.cloud.gateway.routes[1].uri=lb://citas-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/citas/**

spring.cloud.gateway.routes[2].id=medicos-service
spring.cloud.gateway.routes[2].uri=lb://medicos-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/medicos/**

spring.cloud.gateway.routes[3].id=especialidades-service
spring.cloud.gateway.routes[3].uri=lb://especialidades-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/especialidades/**

spring.cloud.gateway.routes[4].id=historial-service
spring.cloud.gateway.routes[4].uri=lb://historial-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/historiales/**

spring.cloud.gateway.routes[5].id=recetas-service
spring.cloud.gateway.routes[5].uri=lb://recetas-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/recetas/**

spring.cloud.gateway.routes[6].id=pagos-service
spring.cloud.gateway.routes[6].uri=lb://pagos-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/pagos/**

spring.cloud.gateway.routes[7].id=notificaciones-service
spring.cloud.gateway.routes[7].uri=lb://notificaciones-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/notificaciones/**