spring:
  application:
    name: citas-service
  config:
    import: optional:configserver:http://config-server:8888
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: none

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka:8761/eureka/}