spring:
  application:
    name: pacientes-service
  config:
    import: optional:configserver:http://config-server:8888

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka:8761/eureka/}